name: CodeRabbit Reviews

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  coderabbit:
    name: CodeRabbit Review
    runs-on: ubuntu-latest
    
    steps:
      - name: CodeRabbit Review
        uses: coderabbitai/coderabbit-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Add custom configuration
          # config-path: .coderabbit.yaml

